# Monitor settings managed by DMS
# Original monitors from monitors.conf:
monitor=eDP-1,1920x1080@60.01,0x1043,1.0
monitor=HDMI-A-1,2560x1080@60.0,1920x614,1.0
monitor=DP-3,2560x1080@60.0,4480x0,1.0
monitor=DP-3,transform,1

# Fallback por seguridad
monitor=,preferred,auto,1,mirror,eDP-1
